"""empty message

Revision ID: 8ade4643bb55
Revises: 34edefde69b5
Create Date: 2018-08-26 21:19:51.571882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ade4643bb55'
down_revision = '34edefde69b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('winner_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'winner_id')
    # ### end Alembic commands ###
